kind: pipeline
type: docker
name: default

steps:
  - name: build_and_test
    image: python:3.9.0
    commands:
      - apt update && apt-get upgrade -y
      - apt install -y python3-dev python3-cairo build-essential xmlsec1 libxmlsec1-dev pkg-config
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python manage.py migrate
      - python manage.py test